### ISSUE TITLE
🔥 Update Notification 🔥

### ISSUE THREAD

**Issue by jpnykw** [jpnykw/jpnykw.github.io#7]
Reborn my portfolio coming soon.

New things:
1. Redesign by following responsive design.
2. Stylish and useful new UI/UX design.
3. To much compact and power full information of me.

**Comment by JPNYKW** [comment]
Created in adobe XD

[![1](https://snag.gy/A20GLj.jpg)](https://snag.gy/A20GLj.jpg)
[![2](https://snag.gy/wXemVr.jpg)](https://snag.gy/wXemVr.jpg)

**Comment by JPNYKW** [comment]
アイデアメモ
・背景にgif/mp4差し込む
・左右のクロスマップを消しページサークルを中心に

**Comment by JPNYKW** [comment]
背景の [イメージ](https://twitter.com/JPNYKW/status/1120307248297701378)

**Comment by JPNYKW** [comment]
How I do upload the file bigger than 25MB 🤔
